### ISSUE TITLE
ERR invalid DB index in 0.09

### ISSUE THREAD

**Issue by erchn** [ledgetech/lua-resty-redis-connector#38]
I believe [this commit](https://github.com/ledgetech/lua-resty-redis-connector/commit/e8301620837dcdf4397164794657efe6d02ebb5b) introduced a regression in the public `connect` interface that throws the following error when a url without a trailing `/N` exists where `N` is a valid DB index.

```
ERR invalid DB index
```
`connect` is passed a url matching `redis://redis:6379` only.

Additionally, the connection object that is returned is a boolean.

Pinning the version to 0.08 resolves the issue.

**Comment by pintsized** [comment]
Thanks for the report. This is because we now error if `select` fails (except for when connected to a sentinel since that error is only noise), and we seem to lack a test for not providing a DB in the DSN.

On closer inspection there was probably a better fix for this case in the first place - it seems we test `host.db` against nil when it is most likely an empty string.

Fix coming shortly...

**Comment by erchn** [comment]
I’m installing via OPM and the mirrors take a few days to update sometimes, will verify early next week. Thank you.

**Comment by erchn** [comment]
I did end up testing this and it looks good. Thanks!
